HAI 1.2
I HAS A VALUE ITZ A TROOF
VALUE R "WIN"
I HAS A NUMBER1 ITZ A YARN
GIMME NUMBER1INPUT
NUMBER1 R NUMBER1INPUT
I HAS A NUMBER2 ITZ A YARN
GIMME NUMBER2INPUT
NUMBER2 R NUMBER2INPUT
I HAS A ADDNUMBER ITZ A YARN
ADDNUMBER R SUM OF NUMBER1 AN NUMBER2
VISIBLE ADDNUMBER
KTHXBYE