import random
list = []
d = False
s = open("hehe.txt","a")
s2 = open("hehe1.txt","a")
s3 = open("hehe2.txt","a")
s4= open("hehe3.txt","a")
s5 =  open("hehe4.txt","a")
s6 = open("hehe5.txt","a")
s7 = open("hehe6.txt","a")
s8 = open("hehe7.txt","a")
s9 = open("hehe8.txt","a")
s10 = open("hehe9.txt","a")
s11 = open("hehe10.txt","a")
s12= open("hehe11.txt","a")
s13 = open("hehe12.txt","a")
while not d:
    z = random.randint(0,100000000000000000)
    x = z**100
    list.append(z)
    for i in range(0,100):
        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))
        list.append(x)
        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))

            