import random
list = []
d = False
s = open("hehe.txt","a")
s2 = open("hehe1.txt","a")
s3 = open("hehe2.txt","a")
s4= open("hehe3.txt","a")
s5 =  open("hehe4.txt","a")
s6 = open("hehe5.txt","a")
s7 = open("hehe6.txt","a")
s8 = open("hehe7.txt","a")
s9 = open("hehe8.txt","a")
s10 = open("hehe9.txt","a")
s11 = open("hehe10.txt","a")
s12= open("hehe11.txt","a")
s13 = open("hehe12.txt","a")
s30 = open("hehe30.txt","a")
s32 = open("hehe31.txt","a")
s33 = open("hehe32.txt","a")
s34= open("hehe33.txt","a")
s35 =  open("hehe34.txt","a")
s36 = open("hehe35.txt","a")
s37 = open("hehe36.txt","a")
s38 = open("hehe37.txt","a")
s39 = open("hehe48.txt","a")
s40 = open("hehe49.txt","a")
s41 = open("hehe40.txt","a")
s42= open("hehe41.txt","a")
s43 = open("hehe42.txt","a")
while not d:
    z = random.randint(0,100000000000000000)
    x = z**100
    list.append(z)
    for i in range(0,100):
        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))
        s30.write("\n")
        s30.write(str(list))
        s32.write("\n")
        s32.write(str(list))
        s33.write("\n")
        s33.write(str(list))
        s34.write("\n")
        s34.write(str(list))
        s35.write("\n")
        s35.write(str(list))
        s36.write("\n")
        s36.write(str(list))
        s37.write("\n")
        s37.write(str(list))
        s38.write("\n")
        s38.write(str(list))
        s39.write("\n")
        s39.write(str(list))
        s40.write("\n")
        s40.write(str(list))
        s41.write("\n")
        s41.write(str(list))
        s42.write("\n")
        s42.write(str(list))
        s43.write("\n")
        s43.write(str(list))
        list.append(x)
        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))
        s30.write("\n")
        s30.write(str(list))
        s32.write("\n")
        s32.write(str(list))
        s33.write("\n")
        s33.write(str(list))
        s34.write("\n")
        s34.write(str(list))
        s35.write("\n")
        s35.write(str(list))
        s36.write("\n")
        s36.write(str(list))
        s37.write("\n")
        s37.write(str(list))
        s38.write("\n")
        s38.write(str(list))
        s39.write("\n")
        s39.write(str(list))
        s40.write("\n")
        s40.write(str(list))
        s41.write("\n")
        s41.write(str(list))
        s42.write("\n")
        s42.write(str(list))
        s43.write("\n")
        s43.write(str(list))

        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))
        s30.write("\n")
        s30.write(str(list))
        s32.write("\n")
        s32.write(str(list))
        s33.write("\n")
        s33.write(str(list))
        s34.write("\n")
        s34.write(str(list))
        s35.write("\n")
        s35.write(str(list))
        s36.write("\n")
        s36.write(str(list))
        s37.write("\n")
        s37.write(str(list))
        s38.write("\n")
        s38.write(str(list))
        s39.write("\n")
        s39.write(str(list))
        s40.write("\n")
        s40.write(str(list))
        s41.write("\n")
        s41.write(str(list))
        s42.write("\n")
        s42.write(str(list))
        s43.write("\n")
        s43.write(str(list))
        list.append(x)
        s.write("\n")
        s.write(str(list))
        s2.write("\n")
        s2.write(str(list))
        s3.write("\n")
        s3.write(str(list))
        s4.write("\n")
        s4.write(str(list))
        s5.write("\n")
        s5.write(str(list))
        s6.write("\n")
        s6.write(str(list))
        s7.write("\n")
        s7.write(str(list))
        s8.write("\n")
        s8.write(str(list))
        s9.write("\n")
        s9.write(str(list))
        s10.write("\n")
        s10.write(str(list))
        s11.write("\n")
        s11.write(str(list))
        s12.write("\n")
        s12.write(str(list))
        s13.write("\n")
        s13.write(str(list))
        s30.write("\n")
        s30.write(str(list))
        s32.write("\n")
        s32.write(str(list))
        s33.write("\n")
        s33.write(str(list))
        s34.write("\n")
        s34.write(str(list))
        s35.write("\n")
        s35.write(str(list))
        s36.write("\n")
        s36.write(str(list))
        s37.write("\n")
        s37.write(str(list))
        s38.write("\n")
        s38.write(str(list))
        s39.write("\n")
        s39.write(str(list))
        s40.write("\n")
        s40.write(str(list))
        s41.write("\n")
        s41.write(str(list))
        s42.write("\n")
        s42.write(str(list))
        s43.write("\n")
        s43.write(str(list))

            

            