HAI 1.2

I HAS A NAME ITZ A YARN
NAME R "Alex"
I HAS A SECONDNAME ITZ A YARN
NAME R "ALEX"
BOTH SAEM NAME AN "Alex"
O RLY?
    YA RLY
        VISIBLE "MY NAME IS Alex"
    NO WAI
        VISIBLE "My NAME IS ALEX"
OIC
KTHXBYE